-- core table migration
-- table: customers

CREATE TABLE IF NOT EXISTS customers (
  id VARCHAR(36) NOT NULL,
  code VARCHAR(100) NOT NULL,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(50) NOT NULL,
  owner_name VARCHAR(200) NULL,
  owner_address VARCHAR(500) NULL,
  contact_person VARCHAR(200) NULL,
  phone VARCHAR(50) NULL,
  fax VARCHAR(50) NULL,
  address_street VARCHAR(255) NULL,
  address_city VARCHAR(100) NULL,
  address_province VARCHAR(100) NULL,
  izin_sarana_number VARCHAR(100) NULL,
  izin_sarana_expiry_date DATETIME NULL,
  apoteker_name VARCHAR(200) NULL,
  apoteker_address VARCHAR(500) NULL,
  sipa_number VARCHAR(100) NULL,
  sipa_expiry_date DATETIME NULL,
  npwp_number VARCHAR(30) NULL,
  npwp_name VARCHAR(200) NULL,
  npwp_address VARCHAR(500) NULL,
  payment_term_days INT NOT NULL DEFAULT 30,
  credit_limit DECIMAL(18,2) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by VARCHAR(36) NULL,
  updated_by VARCHAR(36) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_customers_code (code),
  KEY idx_customers_name (name),
  KEY idx_customers_type (type),
  KEY idx_customers_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
